development:
  host: "0.0.0.0"
  port: 9001
  protocol: http
  path: vendor/etherpad-lite

test:
  host: "0.0.0.0"
  port: 9001
  protocol: http
  path: vendor/etherpad-lite

production:
  host: "connectedscholar-stage.no.de"
  port: 80
  protocol: http
  apikey: k6GPOaMxzOY41mTuzEmpR1g4h7dc0jWZ
