development:
  host: "0.0.0.0"
  port: 9001
  protocol: http
  path: vendor/etherpad-lite

test:
  host: "0.0.0.0"
  port: 9001
  protocol: http
  path: vendor/etherpad-lite

production:
  host: "connectedscholar.no.de"
  port: 80
  protocol: http
  path: vendor/etherpad-lite

